### ISSUE TITLE
Adding slack notifier

### ISSUE THREAD

**Issue by richardtape** [Behatch/notifiers#1]
Hi!

First, this is awesome. Thank you for putting it together.

Second, are you interested in adding a slack integration? If so then I've written a pretty basic notifier for Slack using their webhooks. I'll make a PR if this is something you're keen on adding, with the notifier and additions to the docs.

**Comment by richardtape** [comment]
Additionally, if you wanted to take a look before saying 'yep, make a PR' here's the branch with the adjustments: https://github.com/richardtape/notifiers/tree/slack-notifier

**Comment by sanpii** [comment]
> are you interested in adding a slack integration?

Yes, but I have just a little question: what is this package work?

I splitted the original source into two repositories, but I don’t really worked on this part since behat 3.

**Comment by richardtape** [comment]
I'm using it on behat 3 and it works great! Also the addition I've made works with behat3. I'll make an official PR.

**Comment by richardtape** [comment]
Here's the PR for adding a slack notifier: https://github.com/Behatch/notifiers/pull/2

**Comment by richardtape** [comment]
Closed by merging https://github.com/Behatch/notifiers/commit/a9972e7c1d46a20acbe5e87229d2e7da87dff249
